name: testing-back

on: pull_request

jobs:
  test-back:
    runs-on: ubuntu-latest # contains Docker + Docker compose
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      # with Docker
      # - name: Run test
      #   run: yarn test:ci
      # Without Docker
      - name: Run test
        run: yarn && yarn test:sqlite
